# Numpy Array

#### Make necessary imports

In [1]:
import numpy as np

#### Set standard size

In [5]:
size = (3, 3)

#### 1. Create empty array and a full array with fill value 3

In [6]:
empty_array = np.empty(size)
full_array = np.full(size, 3)

print(empty_array)
print(full_array)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 1.093e-320]
 [0.000e+000 0.000e+000 0.000e+000]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


#### 2. Create array filled with zeros

In [8]:
zeros_array = np.zeros(size)

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 3. Create array filled with ones

In [9]:
ones_array = np.ones(size)

print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 4. Check whether a Numpy array contains a specified row

In [11]:
desired_row = [1, 1, 1]

print(desired_row in ones_array.tolist())
print(desired_row in zeros_array.tolist())

True
False


#### 5. Remove rows in Numpy array that contains non-numeric values

In [15]:
nan_array = np.array([[10.5, 22.5, 3.8, 5],
                      [23.45, 50, 78.7, 3.5],
                      [41, np.nan, np.nan, 0],
                      [20, 50.20, np.nan, 2.5],
                      [18.8, 50.60, 8.8, 58.6]])

new_array = nan_array[~np.isnan(nan_array).any(axis=1)]
print(new_array)

[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [18.8  50.6   8.8  58.6 ]]


#### 6. Remove single-dimensional entries from the shape of an array

In [20]:
ex_array = np.ones((1, 4, 1))

print('Original array:')
print(ex_array)
print(ex_array.shape)

new_ex_array = np.squeeze(ex_array)

print('Squeezed array')
print(new_ex_array)
print(new_ex_array.shape)

Original array:
[[[1.]
  [1.]
  [1.]
  [1.]]]
(1, 4, 1)
Squeezed array
[1. 1. 1. 1.]
(4,)


#### 7. Find the number of occurrences of a sequence in a NumPy array

In [22]:
ex_array = np.array([[2, 8, 9, 4],
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])

count = repr(ex_array).count("9, 4")

print(count)

4


#### 8. Find the most frequent value in a NumPy array

In [25]:
ex_array = np.array([2, 8, 9, 4, 9, 4, 9, 4, 4, 5, 9, 7, 2, 9, 1, 3])

count = np.bincount(ex_array).argmax()

print(count)


9


#### 9. Combining a one and a two-dimensional NumPy Array

In [30]:
array_1d = np.arange(5)
array_2d = np.arange(15).reshape((3, 5))

print(array_1d)
print(array_2d)

for a, b in np.nditer([array_1d, array_2d]):
    print(f'{a}:{b}')

[0 1 2 3 4]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9
0:10
1:11
2:12
3:13
4:14


#### 10. How to build an array of all combinations of two NumPy arrays?

In [35]:
new_array = np.array(np.meshgrid(array_1d, array_2d)).T.reshape(-1, 2)

print(new_array)



[[ 0  0]
 [ 0  1]
 [ 0  2]
 [ 0  3]
 [ 0  4]
 [ 0  5]
 [ 0  6]
 [ 0  7]
 [ 0  8]
 [ 0  9]
 [ 0 10]
 [ 0 11]
 [ 0 12]
 [ 0 13]
 [ 0 14]
 [ 1  0]
 [ 1  1]
 [ 1  2]
 [ 1  3]
 [ 1  4]
 [ 1  5]
 [ 1  6]
 [ 1  7]
 [ 1  8]
 [ 1  9]
 [ 1 10]
 [ 1 11]
 [ 1 12]
 [ 1 13]
 [ 1 14]
 [ 2  0]
 [ 2  1]
 [ 2  2]
 [ 2  3]
 [ 2  4]
 [ 2  5]
 [ 2  6]
 [ 2  7]
 [ 2  8]
 [ 2  9]
 [ 2 10]
 [ 2 11]
 [ 2 12]
 [ 2 13]
 [ 2 14]
 [ 3  0]
 [ 3  1]
 [ 3  2]
 [ 3  3]
 [ 3  4]
 [ 3  5]
 [ 3  6]
 [ 3  7]
 [ 3  8]
 [ 3  9]
 [ 3 10]
 [ 3 11]
 [ 3 12]
 [ 3 13]
 [ 3 14]
 [ 4  0]
 [ 4  1]
 [ 4  2]
 [ 4  3]
 [ 4  4]
 [ 4  5]
 [ 4  6]
 [ 4  7]
 [ 4  8]
 [ 4  9]
 [ 4 10]
 [ 4 11]
 [ 4 12]
 [ 4 13]
 [ 4 14]]


#### 11. How to add a border around a NumPy array?

In [37]:
ones_array = np.ones(size)

# "mode" and "constant_values" are optional
padded_array = np.pad(ones_array, pad_width=1, mode='constant', constant_values=0)

print(ones_array)
print(padded_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 12. How to compare two NumPy arrays?

In [41]:
ex_array1 = np.ones(size)
ex_array2 = [[1, 1, 1],
             [1, 1, 1],
             [1, 1, 1]]
ex_array3 = np.zeros(size)

print('Array 1 and Array 2:', end='\n    ')
print(np.array_equal(ex_array1, ex_array2))
print('Array 1 and Array 3:', end='\n    ')
print(np.array_equal(ex_array1, ex_array3))


Array 1 and Array 2:
    True
Array 1 and Array 3:
    False


#### 13. How to check whether specified values are present in NumPy array?

In [42]:
ex_array = np.array([[2, 8, 9, 4],
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])

print(4 in ex_array)
print(1 in ex_array)
print(3 in ex_array)
print(12 in ex_array)


True
False
True
False


#### 14. How to get all 2D diagonals of a 3D NumPy array?

In [44]:
ex_array = np.arange(3 * 4 * 5).reshape(3, 4, 5)

diagonal = np.diagonal(ex_array, axis1=1, axis2=2)

print('Original array:')
print(ex_array)
print('\nDiagonals array:')
print(diagonal)

Original array:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

Diagonals array:
[[ 0  6 12 18]
 [20 26 32 38]
 [40 46 52 58]]


#### 15. Flatten a Matrix in Python using NumPy

In [46]:
ex_array = np.array([[2, 8, 9, 4],
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])

flat_array = ex_array.flatten()

print('Original array:')
print(ex_array)
print('\nFlattened array:')
print(flat_array)

Original array:
[[2 8 9 4]
 [9 4 9 4]
 [4 5 9 7]
 [2 9 4 3]]

Flattened array:
[2 8 9 4 9 4 9 4 4 5 9 7 2 9 4 3]


#### 16. Flatten a 2d numpy array into 1d array (the same as above)

In [47]:
ex_array = np.array([[2, 8, 9, 4],
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])

flat_array = ex_array.flatten()

print('Original array:')
print(ex_array)
print('\nFlattened array:')
print(flat_array)

Original array:
[[2 8 9 4]
 [9 4 9 4]
 [4 5 9 7]
 [2 9 4 3]]

Flattened array:
[2 8 9 4 9 4 9 4 4 5 9 7 2 9 4 3]


#### 17. Move axes of an array to new positions

In [50]:
ex_array = np.zeros((2, 3, 4))

move_x = np.moveaxis(ex_array, -1, 0)
move_y = np.moveaxis(ex_array, 0, -1)

print('Original array:')
print(ex_array)
print('\nX axis moved:')
print(move_x)
print('\nY axis moved:')
print(move_y)

Original array:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

X axis moved:
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

Y axis moved:
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


#### 18. Interchange two axes of an array

In [51]:
ex_array = np.array([[1, 2, 3]])

swapped = np.swapaxes(ex_array, 0, 1)

print('Original array:')
print(ex_array)
print('\nSwapped axis array:')
print(swapped)

Original array:
[[1 2 3]]

Swapped axis array:
[[1]
 [2]
 [3]]


#### 19. NumPy – Fibonacci Series using Binet Formula
The formula:

$f(n) = [(\alpha)^n - (\beta)^n] * \frac{1}{\sqrt{5}}$

Where $\alpha = \frac{1+\sqrt{5}}{2}$ and $\beta = \frac{1-\sqrt{5}}{2}$

In [52]:
array = np.arange(1, 11)

# For simplicity
sqrt_five = np.sqrt(5)
alpha = (1 + sqrt_five) / 2
beta = (1 - sqrt_five) / 2

binet = np.rint(((alpha ** array) - (beta ** array)) / sqrt_five)
print(f'The first {len(array)} elements of Fibonacci sequence are {binet}')

The first 10 elements of Fibonacci sequence are [ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.]


#### 20. Counts the number of non-zero values in the array

In [53]:
ex_array = [[0, 1, 2, 3, 0],
            [0, 5, 6, 0, 7],
            [9, 0, 1, 0, 0]]

count = np.count_nonzero(ex_array)

print(count)


8


#### 21. Count the number of elements along a given axis

In [57]:
ex_array = np.arange(8).reshape(2, 4)

print('Original array:')
print(ex_array)
print('\nSize of the whole array:')
print(np.size(ex_array))
print('Number of rows in x axis:')
print(np.size(ex_array, 0))
print('Number of cols in y axis:')
print(np.size(ex_array, 1))


Original array:
[[0 1 2 3]
 [4 5 6 7]]

Size of the whole array:
8
Number of rows in x axis:
2
Number of cols in y axis:
4


#### 22. Trim the leading and/or trailing zeros from a 1-D array

In [58]:
ex_array = np.array([0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0])

trimmed = np.trim_zeros(ex_array)

print('Original array:')
print(ex_array)
print('\nTrimmed array:')
print(trimmed)


Original array:
[ 0  0  0  0  1  5  7  0  6  2  9  0 10  0  0]

Trimmed array:
[ 1  5  7  0  6  2  9  0 10]


#### 23. Change data type of given numpy array

In [59]:
ex_array = np.array([0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0])
new_array = ex_array.astype('float64')

print(ex_array.dtype)
print(new_array.dtype)

int32
float64


#### 24. Reverse a numpy array

In [62]:
ex_array = np.array([[0, 1, 2, 3, 0],
                    [0, 5, 6, 0, 7],
                    [9, 0, 1, 0, 0]])

flipped = np.flip(ex_array)

print('Original array:')
print(ex_array)
print('\nFlipped array:')
print(flipped)


Original array:
[[0 1 2 3 0]
 [0 5 6 0 7]
 [9 0 1 0 0]]

Flipped array:
[[0 0 1 0 9]
 [7 0 6 5 0]
 [0 3 2 1 0]]


#### 25. How to make a NumPy array read-only?

In [64]:
ex_array = np.zeros(10)

print('Before any changes:')
print(ex_array)

ex_array[1] = 2
print('After first change:')
print(ex_array)

ex_array.flags.writeable = False
print('After making array immutable and attempting a change:')
ex_array[1] = 7

Before any changes:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After first change:
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
After making array immutable and attempting a change:


ValueError: assignment destination is read-only

# Questions on NumPy Matrix

#### 1. Get the maximum value from given matrix

In [66]:
ex_array = np.array([[11, 12, 13],
                     [14, 15, 16],
                     [17, 15, 11],
                     [12, 14, 15]])

max_value = np.amax(ex_array)

print(max_value)


6
17


#### 2. Get the minimum value from given matrix

In [67]:
ex_array = np.array([[11, 12, 13],
                     [14, 15, 16],
                     [17, 15, 11],
                     [12, 14, 15]])

max_value = np.amin(ex_array)

print(max_value)

11


#### 3. Find the number of rows and columns of a given matrix using NumPy

In [68]:
ex_array = np.array([[11, 12, 13],
                     [14, 15, 16],
                     [17, 15, 11],
                     [12, 14, 15]])

print(ex_array.shape)

(4, 3)


#### 4. Select the elements from a given matrix

In [72]:
ex_array = np.array([[11, 2, 13],
                     [14, 5, 16],
                     [17, 15, 9],
                     [12, 4, 15]])

new_array = np.select(ex_array <= 11, ex_array)

print('Original array:')
print(ex_array)
print('\nNew array:')
print(new_array)


Original array:
[[11  2 13]
 [14  5 16]
 [17 15  9]
 [12  4 15]]

New array:
[11  2  9]


#### 5. Find the sum of values in a matrix

In [74]:
ex_array = np.array([[11, 2, 13],
                     [14, 5, 16],
                     [17, 15, 9],
                     [12, 4, 15]])

array_sum = ex_array.sum()

print(array_sum)

133


#### 6. Calculate the sum of the diagonal elements of a NumPy array

In [76]:
ex_array = np.array([[11, 2, 13],
                     [14, 5, 16],
                     [17, 15, 9]])

trace = np.trace(ex_array)

print('Original matrix:')
print(ex_array)
print('\nDiagonal sum:')
print(trace)


Original matrix:
[[11  2 13]
 [14  5 16]
 [17 15  9]]

Diagonal sum:
25


#### 7. Adding and Subtracting Matrices in Python

In [80]:
ex_array1 = np.array([[11, 2, 13],
                     [14, 5, 16],
                     [17, 15, 9]])

ex_array2 = np.array([[2, 8, 4],
                   [9, 4, 1],
                   [4, 5, 10]])

matrix_sum = np.add(ex_array1, ex_array2)
matrix_sub = np.subtract(ex_array1, ex_array2)

print(f'Sum:\n{matrix_sum}')
print(f'\nSubtraction:\n{matrix_sub}')

Sum:
[[13 10 17]
 [23  9 17]
 [21 20 19]]

Subtraction:
[[ 9 -6  9]
 [ 5  1 15]
 [13 10 -1]]


#### 8. Ways to add row/columns in numpy array

In [84]:
ex_array = np.array([[1, 2, 3],
                     [45, 4, 7],
                     [9, 6, 10]])

to_be_added = np.array([0, 0, 0])

added_array = np.hstack((ex_array, np.atleast_2d(to_be_added).T))

print(f'Original array:\n{ex_array}')
print(f'\nColumn added array:\n{added_array}')

Original array:
[[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
Column added array:
[[ 1  2  3  0]
 [45  4  7  0]
 [ 9  6 10  0]]


#### 9. Matrix Multiplication in NumPy

In [85]:
ex_array1 = np.array([[11, 2, 13],
                     [14, 5, 16],
                     [17, 15, 9]])

ex_array2 = np.array([[2, 8, 4],
                   [9, 4, 1],
                   [4, 5, 10]])

mult = np.dot(ex_array1, ex_array2)

print(mult)

[[ 92 161 176]
 [137 212 221]
 [205 241 173]]


#### 10. Get the eigen values of a matrix

In [87]:
ex_array = np.array([[1, 2, 3],
                     [45, 4, 7],
                     [9, 6, 10]])

eigen_values, eigen_vectors = np.linalg.eig(ex_array)

print(f'Eigen values:\n{eigen_values}')

Eigen values:
[-5.69973694  0.64746042 20.05227652]

Eigen vectors:
[[ 0.16267116 -0.02470318  0.17761459]
 [-0.94916409 -0.83045413  0.76686194]
 [ 0.2694914   0.55653903  0.61674616]]


#### 11. How to Calculate the determinant of a matrix using NumPy?

In [88]:
ex_array = np.array([[1, 2, 3],
                     [45, 4, 7],
                     [9, 6, 10]])

det = np.linalg.det(ex_array)

print(det)

-73.99999999999983


#### 12. How to inverse a matrix using NumPy

In [89]:
ex_array = np.array([[6, 1, 1, 3],
                  [4, -2, 5, 1],
                  [2, 8, 7, 6],
                  [3, 1, 9, 7]])

inverse = np.linalg.inv(ex_array)

print(inverse)

[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


#### 13. How to count the frequency of unique values in NumPy array?

In [91]:
ex_array = np.array([[6, 1, 1, 3],
                  [4, -2, 5, 1],
                  [2, 8, 7, 6],
                  [3, 1, 9, 7]])

unique, freq = np.unique(ex_array, return_counts=True)
count = np.asarray((unique, freq))

print(count)


[[-2  1  2  3  4  5  6  7  8  9]
 [ 1  4  1  2  1  1  2  2  1  1]]


#### 14. Multiply matrices of complex numbers using NumPy in Python

In [94]:
ex_array1 = np.array([2+3j, 4+5j])
ex_array2 = np.array([8+7j, 5+6j])

mult = np.vdot(ex_array1, ex_array2)

print(f'Matrix 1:\n{ex_array1}')
print(f'\nMatrix 2:\n{ex_array2}')
print(f'\nMultiplication:\n{mult}')

Matrix 1:
[2.+3.j 4.+5.j]

Matrix 2:
[8.+7.j 5.+6.j]

Multiplication:
(87-11j)


#### 15. Compute the outer product of two given vectors using NumPy in Python

In [95]:
ex_array1 = np.array([[11, 2, 13],
                     [14, 5, 16],
                     [17, 15, 9]])

ex_array2 = np.array([[2, 8, 4],
                   [9, 4, 1],
                   [4, 5, 10]])

outer = np.outer(ex_array1, ex_array2)

print(outer)

[[ 22  88  44  99  44  11  44  55 110]
 [  4  16   8  18   8   2   8  10  20]
 [ 26 104  52 117  52  13  52  65 130]
 [ 28 112  56 126  56  14  56  70 140]
 [ 10  40  20  45  20   5  20  25  50]
 [ 32 128  64 144  64  16  64  80 160]
 [ 34 136  68 153  68  17  68  85 170]
 [ 30 120  60 135  60  15  60  75 150]
 [ 18  72  36  81  36   9  36  45  90]]


#### 16. Calculate inner, outer, and cross products of matrices and vectors using NumPy

In [98]:
ex_vec1 = np.array([2, 6])
ex_vec2 = np.array([3, 10])

ex_array1 = np.array([[2, 3, 4],
                      [3, 2, 9]])
ex_array2 = np.array([[1, 5, 0],
                      [5, 10, 3]])

inner_vec = np.inner(ex_vec1, ex_vec2)
inner_array = np.inner(ex_array1, ex_array2)

print(f'Inner product of vectors:\n{inner_vec}')
print(f'\nInner product of matrices:\n{inner_array}')

outer_vec = np.outer(ex_vec1, ex_vec2)
outer_array = np.outer(ex_array1, ex_array2)

print(f'\n\nOuter product of vectors:\n{outer_vec}')
print(f'\nOuter product of matrices:\n{outer_array}')

cross_vec = np.cross(ex_vec1, ex_vec2)
cross_array = np.cross(ex_array1, ex_array2)

print(f'\n\nCross product of vectors:\n{cross_vec}')
print(f'\nCross product of matrices:\n{cross_array}')

Inner product of vectors:
66

Inner product of matrices:
[[17 52]
 [13 62]]


Outer product of vectors:
[[ 6 20]
 [18 60]]

Outer product of matrices:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


Cross product of vectors:
2

Cross product of matrices:
[[-20   4   7]
 [-84  36  20]]


#### 17. Compute the covariance matrix of two given NumPy arrays

In [99]:
ex_array1 = np.array([[2, 3, 4],
                      [3, 2, 9]])
ex_array2 = np.array([[1, 5, 0],
                      [5, 10, 3]])

cov = np.cov(ex_array1, ex_array2)

print(cov)

[[  1.           3.          -0.5         -1.        ]
 [  3.          14.33333333  -7.5        -11.        ]
 [ -0.5         -7.5          7.           9.5       ]
 [ -1.         -11.           9.5         13.        ]]


#### 18. Convert covariance matrix to correlation matrix using Python

In [100]:
v = np.sqrt(np.diag(cov))
outer_v = np.outer(v, v)
correlation = cov / outer_v
correlation[cov == 0] = 0

print(correlation)

[[ 1.          0.79240582 -0.18898224 -0.2773501 ]
 [ 0.79240582  1.         -0.74875312 -0.80583738]
 [-0.18898224 -0.74875312  1.          0.99587059]
 [-0.2773501  -0.80583738  0.99587059  1.        ]]


#### 19. Compute the Kronecker product of two mulitdimension NumPy arrays

In [101]:
ex_array1 = np.array([[2, 3, 4],
                      [3, 2, 9]])
ex_array2 = np.array([[1, 5, 0],
                      [5, 10, 3]])

kronecker = np.kron(ex_array1, ex_array2)

print(kronecker)

[[ 2 10  0  3 15  0  4 20  0]
 [10 20  6 15 30  9 20 40 12]
 [ 3 15  0  2 10  0  9 45  0]
 [15 30  9 10 20  6 45 90 27]]


#### 20. Convert the matrix into a list

In [105]:
ex_array = np.array([[11, 2, 13],
                     [14, 5, 16],
                     [17, 15, 9]])

list_array = ex_array.tolist()

print(list_array)
print(type(list_array))

[[11, 2, 13], [14, 5, 16], [17, 15, 9]]
<class 'list'>


# Questions on NumPy Indexing

#### 1. Replace NumPy array elements that doesn’t satisfy the given condition

In [107]:
ex_array = np.array([[11, 2, 13],
                     [4, 5, 16],
                     [17, 15, 9]])

print(f'Original array:\n{ex_array}')

print('\nReplace all values that are larger than 10 with 0')
ex_array[ex_array > 10] = 0

print(f'\nNew array:\n{ex_array}')

Original array:
[[11  2 13]
 [ 4  5 16]
 [17 15  9]]

Replace all values that are larger than 10 with 0

New array:
[[0 2 0]
 [4 5 0]
 [0 0 9]]


#### 2. Return the indices of elements where the given condition is satisfied

In [111]:
ex_array = np.array([[11, 2, 13],
                     [4, 5, 16],
                     [17, 15, 9]])

indices = np.where(ex_array > 10)
print(f'Indices of elementes that are greater than 10:\n{indices}')
print(f'\nElements that are greater than 10:\n{ex_array[indices]}')

Indices of elementes that are greater than 10:
(array([0, 0, 1, 2, 2], dtype=int64), array([0, 2, 2, 0, 1], dtype=int64))

Elements that are greater than 10:
[11 13 16 17 15]


#### 3. Replace NaN values with average of columns

In [113]:
ex_array = np.array([[1.3, 2.5, 3.6, np.nan],
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])

print(f'Original array:\n{ex_array}')

col_mean = np.nanmean(ex_array, axis=0)
print(f'\nColumns means:\n{col_mean}')

nan_indices = np.where(np.isnan(ex_array))
ex_array[nan_indices] = np.take(col_mean, nan_indices[1])

print(f'\nFinal array:\n{ex_array}')

Original array:
[[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]

Columns means:
[2.  3.  4.5 6. ]

Final array:
[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


#### 4. Replace negative value with zero in numpy array

In [114]:
ex_array = np.array([[11, -2, 13],
                     [4, -5, 16],
                     [-17, 15, -9]])

print(f'Original array:\n{ex_array}')

negative_indices = np.where(ex_array < 0)
ex_array[negative_indices] = 0

print(f'\nFinal array:\n{ex_array}')

Original array:
[[ 11  -2  13]
 [  4  -5  16]
 [-17  15  -9]]

Final array:
[[11  0 13]
 [ 4  0 16]
 [ 0 15  0]]


#### 5. How to get values of an NumPy array at certain index positions?

In [119]:
ex_array1 = np.array([11, 10, 22, 30, 33])
ex_array2 = np.array([1, 15, 60])

print(f'Array 1:\n{ex_array1}')
print(f'Array 2:\n{ex_array2}')

print('\nTake 1 and 15 from Array 2 and put them in 1st and 5th positions of Array 1')

ex_array1.put([0, 4], ex_array2)

print(f'\nFinal array:\n{ex_array1}')

Array 1:
[11 10 22 30 33]
Array 2:
[ 1 15 60]

Take 1 and 15 from Array 2 and put them in 1st and 5th positions of Array 1

Final array:
[ 1 10 22 30 15]


#### 6. Find indices of elements equal to zero in a NumPy array

In [128]:
ex_array = np.array([[6, 0, 1, 3],
                  [4, -2, 0, 1],
                  [2, 8, 0, 0],
                  [0, 1, 0, 7]])

zero_indices = np.argwhere(ex_array == 0)

print(f'\nZero indices:\n{zero_indices}')


Zero indices:
[[0 1]
 [1 2]
 [2 2]
 [2 3]
 [3 0]
 [3 2]]


#### 7. How to Remove columns in Numpy array that contains non-numeric values?

In [130]:
ex_array = np.array([[10.5, 22.5, np.nan],
                  [41, 52.5, np.nan]])

print(f'Original array:\n{ex_array}')

col_removed = ex_array[:, ~np.isnan(ex_array).any(axis=0)]

print(f'\nRemoved non-numeric column array:\n{col_removed}')


Original array:
[[10.5 22.5  nan]
 [41.  52.5  nan]]

Removed non-numeric column array:
[[10.5 22.5]
 [41.  52.5]]


#### 8. How to access different rows of a multidimensional NumPy array?

In [131]:
ex_array = np.array([[10, 20, 30],
                    [40, 5, 66],
                    [70, 88, 94]])

print(f'Original array:\n{ex_array}')

# Accessing first and last rows
new_array = ex_array[[0, 2]]
print(f'\nAccessed rows:\n{new_array}')


Original array:
[[10 20 30]
 [40  5 66]
 [70 88 94]]

Accessed rows:
[[10 20 30]
 [70 88 94]]


#### 9. Get row numbers of NumPy array having element larger than X

In [132]:
ex_array = np.array([[1, 2, 3, 4, 5],
                  [10, -3, 30, 4, 5],
                  [3, 2, 5, -4, 5],
                  [9, 7, 3, 6, 5]])

x = 6
new_array = np.where(np.any(ex_array > x, axis=1))

print(new_array)

(array([1, 3], dtype=int64),)


#### 10. Get filled with the diagonals of NumPy array

In [134]:
ex_array = np.array([[1, 2, 3, 4, 5],
                  [10, -3, 30, 4, 5],
                  [3, 2, 5, -4, 5],
                  [9, 7, 3, 6, 5],
                  [0, 2, 12, 5, 17]])

print(f'Original array:\n{ex_array}')

np.fill_diagonal(ex_array, 0)
print(f'\nArray with diagonal filled with 0:\n{ex_array}')


Original array:
[[ 1  2  3  4  5]
 [10 -3 30  4  5]
 [ 3  2  5 -4  5]
 [ 9  7  3  6  5]
 [ 0  2 12  5 17]]

Array with diagonal filled with 0:
[[ 0  2  3  4  5]
 [10  0 30  4  5]
 [ 3  2  0 -4  5]
 [ 9  7  3  0  5]
 [ 0  2 12  5  0]]


#### 11. Check elements present in the NumPy array

In [135]:
ex_array = np.array([[2, 8, 9, 4],
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])

print(4 in ex_array)
print(1 in ex_array)
print(3 in ex_array)
print(12 in ex_array)

True
False
True
False


#### 12. Combined array index by index

In [ ]:
# Don't know this one

# Questions on NumPy Linear Algebra

#### 1. Find a matrix or vector norm using NumPy

In [136]:
ex_vec = np.arange(10)
vec_norm = np.linalg.norm(ex_vec)

print(vec_norm)

16.881943016134134


#### 2. Calculate the QR decomposition of a given matrix using NumPy

In [138]:
ex_array = np.array([[1, 2, 3],
                     [3, 4, 5]])

q, r = np.linalg.qr(ex_array)
print(f'Q:\n{q}\nR:\n{r}')

Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R:
[[-3.16227766 -4.42718872 -5.69209979]
 [ 0.         -0.63245553 -1.26491106]]


#### 3. Compute the condition number of a given matrix using NumPy

In [139]:
ex_array = np.array([[1, 2, 3],
                     [3, 4, 5]])

condition = np.linalg.cond(ex_array)

print(condition)

12.986944891100837


#### 4. Compute the eigenvalues and right eigenvectors of a given square array using NumPy?

In [141]:
ex_array = np.array([[1, 2, 3],
                     [45, 4, 7],
                     [9, 6, 10]])

eigen_values, eigen_vectors = np.linalg.eig(ex_array)

print(f'Eigen values:\n{eigen_values}')
print(f'\nRight Eigen vectors:\n{eigen_vectors}')

Eigen values:
[-5.69973694  0.64746042 20.05227652]

Right Eigen vectors:
[[ 0.16267116 -0.02470318  0.17761459]
 [-0.94916409 -0.83045413  0.76686194]
 [ 0.2694914   0.55653903  0.61674616]]


#### 5. Calculate the Euclidean distance using NumPy

In [143]:
point1 = np.array([1, 2, 3])
point2 = np.array([1, 1, 1])

distance = np.linalg.norm(point1 - point2)

print(distance)


2.23606797749979


# Questions on NumPy Random

#### 1. Create a Numpy array with random values

#### 2. How to choose elements from the list with different probability using NumPy?

#### 3. How to get weighted random choice in Python?

#### 4. Generate Random Numbers From The Uniform Distribution using NumPy

#### 5. Get Random Elements form geometric distribution

#### 6. Get Random elements from Laplace distribution

#### 7. Return a Matrix of random values from a uniform distribution

#### 8. Return a Matrix of random values from a Gaussian distribution